python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_base_best.json
python3 bert_for_ner_seqeval.py news_fine_tune_ner_bert_base_best.json
python3 bert_for_ner_seqeval.py news_fine_tune_ner_bert_large_best.json
python3 bert_for_ner_seqeval.py news_fine_tune_ner_finbert_best.json
python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_large_best.json

python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_large_transfer_learning_cr.json
python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_large_transfer_learning_conll.json



python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_large_transfer_learning_train_cr_test_conll.json
python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_large_transfer_learning_train_finer_test_conll.json


python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_large_transfer_learning_combine.json
python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_large_transfer_learning_train_combined_test_conll.json

python3 bert_for_ner_seqeval.py news_fine_tune_ner_roberta_large_transfer_learning_train_conll_test_conll.json

python3 gpt_4o_api_run.py
python3 llama_3_70B_api_run.py
python3 llama_31_70B_api_run.py
python3 llama_31_405B_api_run.py
